import { App, normalizePath, TFile } from 'obsidian';
import { NoteAnalysis, SimilarityResult } from '../types';

function dateStr(): string {
  return new Date().toISOString().slice(0, 10).replace(/-/g, '');
}

function safeName(name: string, maxLen = 30): string {
  return name.replace(/\s+/g, '-').slice(0, maxLen);
}

function stripFrontmatter(raw: string): string {
  if (!raw.startsWith('---')) return raw;
  const end = raw.indexOf('\n---', 3);
  if (end === -1) return raw;
  return raw.slice(end + 4).trimStart();
}

function extractSectionContent(rawContent: string, heading: string): string {
  const body = stripFrontmatter(rawContent);
  const lines = body.split('\n');
  let inSection = false;
  let headingLevel = 0;
  const sectionLines: string[] = [];

  for (const line of lines) {
    const m = line.match(/^(#{1,6})\s+(.+)/);
    if (m) {
      const level = m[1].length;
      const text = m[2].trim();
      if (inSection) {
        if (level <= headingLevel) break;
        sectionLines.push(line);
      } else if (text.toLowerCase() === heading.toLowerCase()) {
        inSection = true;
        headingLevel = level;
      }
    } else if (inSection) {
      sectionLines.push(line);
    }
  }

  return sectionLines.join('\n').trim();
}

export class MergeDraftGenerator {
  constructor(private app: App, private draftFolder: string) {}

  async generate(
    analyses: NoteAnalysis[],
    result: SimilarityResult
  ): Promise<TFile> {
    const topic = result.commonHeadings[0] ?? analyses[0].basename;
    const baseName = `merge-draft-${safeName(topic)}-${dateStr()}`;
    const path = await this.buildSafePath(this.draftFolder, baseName);
    const content = this.buildContent(analyses, result);

    await this.ensureFolder(this.draftFolder);
    return this.app.vault.create(path, content);
  }

  private async buildSafePath(folder: string, baseName: string): Promise<string> {
    let candidate = normalizePath(`${folder}/${baseName}.md`);
    if (!this.app.vault.getAbstractFileByPath(candidate)) return candidate;

    let i = 2;
    while (true) {
      candidate = normalizePath(`${folder}/${baseName}-${i}.md`);
      if (!this.app.vault.getAbstractFileByPath(candidate)) return candidate;
      i++;
    }
  }

  private async ensureFolder(folderPath: string): Promise<void> {
    if (!this.app.vault.getAbstractFileByPath(folderPath)) {
      await this.app.vault.createFolder(folderPath);
    }
  }

  private renderSection(analyses: NoteAnalysis[], heading: string): string {
    const parts = analyses.map(a => ({
      name: a.basename,
      content: extractSectionContent(a.rawContent, heading),
    })).filter(p => p.content.length > 0);

    if (parts.length === 0) return `### ${heading}\n\n`;
    if (parts.length === 1) return `### ${heading}\n\n${parts[0].content}\n`;
    if (parts[0].content === parts[1].content) return `### ${heading}\n\n${parts[0].content}\n`;
    return `### ${heading}\n\n> From **${parts[0].name}**\n\n${parts[0].content}\n\n> From **${parts[1].name}**\n\n${parts[1].content}\n`;
  }

  private buildContent(analyses: NoteAnalysis[], r: SimilarityResult): string {
    const sourceLinks = analyses.map(a => `- [[${a.basename}]]`).join('\n');
    const chips = (arr: string[]) => arr.length > 0 ? arr.map(s => `\`${s}\``).join(', ') : '—';

    const sections = r.commonHeadings.length > 0
      ? r.commonHeadings.map(h => this.renderSection(analyses, h)).join('\n')
      : '—';

    return `# Merge Draft

> This is a draft for merging similar notes. Original notes have not been modified.

## Source Notes

${sourceLinks}

## Common Sections

${sections}

## Common Keywords

${chips(r.commonKeywords)}

---
*Generated by Dualyze Notes*
`;
  }
}
