import { App, normalizePath, TFile } from 'obsidian';
import { NoteAnalysis, SimilarityResult } from '../types';

function dateStr(): string {
  return new Date().toISOString().slice(0, 10).replace(/-/g, '');
}

function safeName(name: string, maxLen = 30): string {
  return name.replace(/\s+/g, '-').slice(0, maxLen);
}

export class MergeDraftGenerator {
  constructor(private app: App, private draftFolder: string) {}

  async generate(
    analyses: NoteAnalysis[],
    result: SimilarityResult
  ): Promise<TFile> {
    const topic = result.commonHeadings[0] ?? analyses[0].basename;
    const baseName = `merge-draft-${safeName(topic)}-${dateStr()}`;
    const path = await this.buildSafePath(this.draftFolder, baseName);
    const content = this.buildContent(analyses, result);

    await this.ensureFolder(this.draftFolder);
    return this.app.vault.create(path, content);
  }

  private async buildSafePath(folder: string, baseName: string): Promise<string> {
    let candidate = normalizePath(`${folder}/${baseName}.md`);
    if (!this.app.vault.getAbstractFileByPath(candidate)) return candidate;

    let i = 2;
    while (true) {
      candidate = normalizePath(`${folder}/${baseName}-${i}.md`);
      if (!this.app.vault.getAbstractFileByPath(candidate)) return candidate;
      i++;
    }
  }

  private async ensureFolder(folderPath: string): Promise<void> {
    if (!this.app.vault.getAbstractFileByPath(folderPath)) {
      await this.app.vault.createFolder(folderPath);
    }
  }

  private buildContent(analyses: NoteAnalysis[], r: SimilarityResult): string {
    const sourceLinks = analyses.map(a => `- [[${a.basename}]]`).join('\n');
    const chips = (arr: string[]) => arr.length > 0 ? arr.map(s => `\`${s}\``).join(', ') : '—';

    return `# Merge Draft

> This is a draft for merging similar notes. Original notes have not been modified.

## Source Notes

${sourceLinks}

## Common Headings

${r.commonHeadings.length > 0 ? r.commonHeadings.map(h => `### ${h}`).join('\n\n') : '—'}

## Common Keywords

${chips(r.commonKeywords)}

---

## Draft Content

> Fill in the merged content below. Refer to the source notes above.

---
*Generated by Dualyze Notes*
`;
  }
}
