import { App, normalizePath, TFile } from 'obsidian';
import { NoteAnalysis, SimilarityResult } from '../types';

function dateStr(): string {
  return new Date().toISOString().slice(0, 10).replace(/-/g, '');
}

function safeName(name: string, maxLen = 30): string {
  return name.replace(/\s+/g, '-').slice(0, maxLen);
}

export class ReportGenerator {
  constructor(private app: App, private reportFolder: string) {}

  async generate(
    a: NoteAnalysis,
    b: NoteAnalysis,
    result: SimilarityResult
  ): Promise<TFile> {
    const baseName = `comparison-${safeName(a.basename)}-vs-${safeName(b.basename)}-${dateStr()}`;
    const path = await this.buildSafePath(this.reportFolder, baseName);
    const content = this.buildContent(a, b, result);

    await this.ensureFolder(this.reportFolder);
    return this.app.vault.create(path, content);
  }

  private async buildSafePath(folder: string, baseName: string): Promise<string> {
    let candidate = normalizePath(`${folder}/${baseName}.md`);
    if (!this.app.vault.getAbstractFileByPath(candidate)) return candidate;

    let i = 2;
    while (true) {
      candidate = normalizePath(`${folder}/${baseName}-${i}.md`);
      if (!this.app.vault.getAbstractFileByPath(candidate)) return candidate;
      i++;
    }
  }

  private async ensureFolder(folderPath: string): Promise<void> {
    if (!this.app.vault.getAbstractFileByPath(folderPath)) {
      await this.app.vault.createFolder(folderPath);
    }
  }

  private buildContent(a: NoteAnalysis, b: NoteAnalysis, r: SimilarityResult): string {
    const pct = (n: number) => `${(n * 100).toFixed(1)}%`;
    const chips = (arr: string[]) => arr.length > 0 ? arr.map(s => `\`${s}\``).join(', ') : '—';

    return `# Comparison: [[${a.basename}]] vs [[${b.basename}]]

## Overall Score

**${pct(r.overallScore)}** — ${r.label}

## Score Breakdown

| Dimension | Score |
|---|---|
| Title | ${pct(r.titleScore)} |
| Headings | ${pct(r.headingScore)} |
| Tags | ${pct(r.tagScore)} |
| Links | ${pct(r.linkScore)} |
| Content | ${pct(r.contentScore)} |

## Common Elements

**Headings:** ${chips(r.commonHeadings)}
**Tags:** ${chips(r.commonTags)}
**Links:** ${chips(r.commonLinks)}
**Keywords:** ${chips(r.commonKeywords)}

## Unique to [[${a.basename}]]

**Headings:** ${chips(r.uniqueHeadingsA)}
**Keywords:** ${chips(r.uniqueKeywordsA)}

## Unique to [[${b.basename}]]

**Headings:** ${chips(r.uniqueHeadingsB)}
**Keywords:** ${chips(r.uniqueKeywordsB)}

---
*Generated by Dualyze Notes*
`;
  }
}
